version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    volumes:
      - ./src/api:/app
      - ./data:/data
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - API_DEBUG=${API_DEBUG:-true}
      - API_LOG_LEVEL=${API_LOG_LEVEL:-debug}
      - API_SECRET_KEY=${API_SECRET_KEY:-development_secret_key}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-ai_ocr}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
      - MINIO_URL=http://${MINIO_HOST:-minio}:${MINIO_PORT:-9000}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-documents}
      - PROCESSOR_URL=http://${PROCESSOR_HOST:-processor}:${PROCESSOR_PORT:-8080}
      - MAX_DOCUMENT_SIZE=${MAX_DOCUMENT_SIZE:-50000000}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-xlsx,xls,csv}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,http://localhost:8000}
      - TOKEN_EXPIRY=${TOKEN_EXPIRY:-86400}
    depends_on:
      - db
      - redis
      - minio
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  processor:
    build:
      context: .
      dockerfile: Dockerfile
      target: processor
    volumes:
      - ./src/processor:/app
      - ./data:/data
    environment:
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-ai_ocr}
      - REDIS_URL=redis://${REDIS_HOST:-redis}:${REDIS_PORT:-6379}/${REDIS_DB:-0}
      - MINIO_URL=http://${MINIO_HOST:-minio}:${MINIO_PORT:-9000}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_BUCKET=${MINIO_BUCKET:-documents}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o}
      - MODEL_TEMPERATURE=${MODEL_TEMPERATURE:-0.1}
      - MODEL_API_KEY=${MODEL_API_KEY:-your_api_key_here}
      - PROCESSOR_WORKERS=${PROCESSOR_WORKERS:-2}
    depends_on:
      - redis
      - minio
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-ai_ocr}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/db/init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio-data:/data
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "9001:9001"
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  minio-data:
